listSpell = document.querySelectorAll('div.col.col-auto.bg-solobeige.pt-2.rounded.h-100 div.row.row-cols-2.p-0.m-0 .class-spell') 
arrayListSpell = Array.from(listSpell) 
delay = (delayInms) => {
    return new Promise(resolve => setTimeout(resolve, delayInms));
  };

arrayListSpell.forEach(async (x, i)=>{
    await delay(100*i)
    x.click()
    document.querySelector('div.pl-1:nth-child(6)').click()
    spellInfo = document.querySelector('#spell-infos')
    console.log(spellInfo)
    
})


listSpell = document.querySelectorAll('div.col.col-auto.bg-solobeige.pt-2.rounded.h-100 div.row.row-cols-2.p-0.m-0 .class-spell') 
arrayListSpell = Array.from(listSpell) 

t = arrayListSpell.map((x)=>{
    c= x.querySelector('div.row div.font-weight-bold').textContent
    return c.replace(/\s?#.*$/, '')
})
console.log(t);

stringSpellEn = [
  "Natural Attack",
  "Aggressive Glyph",
  "Earth Armour",
  "Spell Rebound",
  "Blindness",
  "Glowing Armour",
  "Cloudy Attack",
  "Aqueous Armour",
  "Immunity",
  "Wind Armour",
  "Bubble",
  "Truce",
  "Art of Staff",
  "Backlash",
  "Glyph of Blindness",
  "Teleportation",
  "Burning Glyph",
  "Feca Shield",
  "Paralyzing Glyph",
  "Glyph of Silence",
  "Summoning of Feca Dopple",

  "Bear Cry",
  "Summoning of Tofu",
  "Ghostly Claw",
  "Animal Blessing",
  "Feline Movement",
  "Summoning of Gobball",
  "Toad",
  "Summoning of Prespic",
  "Whip",
  "High-Energy Shot",
  "Crow",
  "Lashing Claw",
  "Animal Healing",
  "Summoning of Boar",
  "Punch of the Crackler",
  "Natural Defence",
  "Fangs of Boowolf",
  "Summoning of Bwork Magus",
  "Summoning of Crackler",
  "Summoning of Red Wyrmling",
  "Summoning of Osamodas Dopple",

  "Coins Throwing",
  "Living Bag",
  "Shovel Throwing",
  "Ghostly Shovel",
  "Fortune",
  "Pandora's Box",
  "Mound",
  "Reducing Key",
  "Prime of Life",
  "Unsummoning",
  "Greed",
  "Shovel Kiss",
  "Clumsiness",
  "Mass Clumsiness",
  "Acceleration",
  "Shovel of Judgement",
  "Slaughtering Shovel",
  "Bribery",
  "Living Shovel",
  "Living Chest",
  "Summoning of Enutrof Dopple",

  "Tricky Trap",
  "Invisibility",
  "Deviousness",
  "Insidious Poison",
  "Mistake",
  "Tricky Blow",
  "Double",
  "Location",
  "Mass Trap",
  "Invisibility of Others",
  "Poisoned Trap",
  "Chakra Concentration",
  "Paralyzing Trap",
  "Trap of Silence",
  "Repelling Trap",
  "Fear",
  "Con",
  "Chakra Impulse",
  "Lethal Attack",
  "Lethal Trap",
  "Summoning of Sram Dopple",

  "Slow Down",
  "Hand",
  "Counter",
  "Frostbite",
  "Xelor's Sandglass",
  "Dark Ray",
  "Teleportation",
  "Shriveling",
  "Haziness",
  "Temporal Dust",
  "Time Theft",
  "Homing Hand",
  "Devotion",
  "Flight",
  "Loss of Motivation",
  "Blinding Protection",
  "Mummification",
  "Clock",
  "Xelor's Punch",
  "Xelor's Dial",
  "Summoning of Xelor Dopple",

  "Heads or Tails",
  "Ecaflip's Luck",
  "Feline Leap",
  "Bluff",
  "Perception",
  "Repercussion",
  "Clover",
  "All or Nothing",
  "Roulette",
  "Topkaj",
  "Rough Tongue",
  "Wheel of Fortune",
  "Summoning Claw",
  "Feline Spirit",
  "Smell",
  "Reflex",
  "Playful Claw",
  "Claw of Ceangal",
  "Rekop",
  "Fate of Ecaflip",
  "Summoning of Ecaflip Dopple",

  "Forbidden Word",
  "Frightening Word",
  "Curative Word",
  "Healing Word",
  "Wounding Word",
  "Stimulating Word",
  "Preventing Word",
  "Draining Word",
  "Revitalizing Word",
  "Regenerating Word",
  "Word of Thorn",
  "Word of Youth",
  "Vampiric Word",
  "Word of Sacrifice",
  "Friendship Word",
  "Paralyzing Word",
  "Lifting Word",
  "Word of Silence",
  "Word of Altruism",
  "Word of Recovery",
  "Summoning of Eniripsa Dopple",

  "Jump",
  "Intimidation",
  "Pressure",
  "Compulsion",
  "Divine Sword",
  "Sword of Fate",
  "Bravery Guide",
  "Increase",
  "Destructive Sword",
  "Cut",
  "Blow",
  "Vitality",
  "Sword of Judgement",
  "Power",
  "Mutilation",
  "Strengthstorm",
  "Celestial Sword",
  "Concentration",
  "Sword of Iop",
  "Iop's Wrath",
  "Summoning of Iop Dopple",

  "Retreat Arrow",
  "Poisoned Arrow",
  "Magic Arrow",
  "Frozen Arrow",
  "Burning Arrow",
  "Distant Shooting",
  "Atonement Arrow",
  "Bat's Eye",
  "Critical Shooting",
  "Paralyzing Arrow",
  "Punitive Arrow",
  "Powerful Shooting",
  "Plaguing Arrow",
  "Lashing Arrow",
  "Tormenting Arrow",
  "Destructive Arrow",
  "Absorptive Arrow",
  "Slow Down Arrow",
  "Explosive Arrow",
  "Bow Skill",
  "Summoning of Cra Dopple",

  "The Block",
  "Bramble",
  "Paralyzing Poison",
  "Dolly Sacrifice",
  "Tear",
  "The Madoll",
  "Soothing Bramble",
  "Sylvan Power",
  "The Sacrificial Doll",
  "Earthquake",
  "Knowledge of Dolls",
  "Manifold Bramble",
  "Tree",
  "Poisoned Wind",
  "The Inflatable",
  "Aggressive Brambles",
  "Wild Grass",
  "Bush Fire",
  "Insolent Bramble",
  "The Ultra-Powerful",
  "Summoning of Sadida Dopple",


  "Forced Punishment",
  "Sacrier's Foot",
  "Attraction",
  "Evasion",
  "Swap",
  "Assault",
  "Nimble Punishment",
  "Dissolution",
  "Bold Punishment",
  "Spiritual Punishment",
  "Sacrifice",
  "Absorption",
  "Vital Punishment",
  "Cooperation",
  "Transposition",
  "Punishment",
  "Fury",
  "Flying Sword",
  "Life Transfer",
  "Bloodthirsty Madness",
  "Summoning of Sacrier Dopple",

  "Boozer",
  "Hangover",
  "Blazing Fist",
  "Terror",
  "Alcoholic Breath",
  "Aqueous Vulnerability",
  "White-Hot Vulnerability",
  "Karcham",
  "Wind Vulnerability",
  "Stabilization",
  "Chamrak",
  "Earth Vulnerability",
  "Stain",
  "Bamboo Milk",
  "Melancholy",
  "Zatoishwan's Wrath",
  "Explosive Flask",
  "Pandatak",
  "Pandiniuras",
  "Spirit Bond",
  "Summoning of Pandawa Dopple"
]
stringSpellEs = [
  "Ataque Natural",
  "Glifo Agresivo",
  "Armadura Terrestre",
  "Reenvío de Hechizo",
  "Ceguera",
  "Armadura Incandescente",
  "Ataque Nuboso",
  "Armadura Acuosa",
  "Inmunidad",
  "Armadura Ventisca",
  "Pompa",
  "Tregua",
  "Ciencia del Palo",
  "Puñalada",
  "Glifo de Ceguera",
  "Teleportación",
  "Glifo Flamígero",
  "Escudo Feca",
  "Glifo de Inmovilización",
  "Glifo de Silencio",
  "Invocación de Dopeul Feca",


  "Grito del Oso",
  "Invocación de Tofu",
  "Garra Espectral",
  "Bendición Animal",
  "Movimiento Felino",
  "Invocación de Jalató",
  "Sapo",
  "Invocación de Prespic",
  "Látigo",
  "Chute Motivador",
  "Cuervo",
  "Garra Azotadora",
  "Curación Animal",
  "Invocación de Jabalí",
  "Golpe del Crujidor",
  "Resistencia Natural",
  "Colmillos del Mediulubo",
  "Invocación de Bwork Mago",
  "Invocación de Crujidor",
  "Invocación de Dragonito Rojo",
  "Invocación de Dopeul Osamodas",

  "Lanzamiento de Monedas",
  "Mochila Animada",
  "Lanzamiento de Pala",
  "Pala Fantasmal",
  "Suerte",
  "Caja de Pandora",
  "Terraplenado",
  "Llave Reductora",
  "Madurez",
  "Desinvocación",
  "Codicia",
  "Jarabe de Pala",
  "Torpeza",
  "Torpeza de Masas",
  "Aceleración",
  "Pala del Juicio",
  "Pala Masacrante",
  "Corrupción",
  "Pala Animada",
  "Cofre Animado",
  "Invocación de Dopeul Anutrof",


  "Trampa Solapada",
  "Invisibilidad",
  "Engaño",
  "Veneno Insidioso",
  "Karadura",
  "Golpe Solapado",
  "Doble",
  "Infravisión",
  "Trampa de Masas",
  "Invisibilidad del Prójimo",
  "Trampa Envenenada",
  "Concentración de Chakra",
  "Trampa de Inmovilización",
  "Trampa de Silencio",
  "Trampa Repulsiva",
  "Miedo",
  "Estafa",
  "Pulsión de Chakra",
  "Ataque Mortal",
  "Trampa Mortal",
  "Invocación de Dopeul Sram",


  "Ralentización",
  "Aguja",
  "Contra",
  "Congelación",
  "Reloj de Arena de Xelor",
  "Rayo Oscuro",
  "Teleportación",
  "Marchitación",
  "Turbio",
  "Polvo Temporal",
  "Robo del Tiempo",
  "Aguja Buscadora",
  "Devoción",
  "Huída",
  "Desmotivación",
  "Protección Cegadora",
  "Momificación",
  "Reloj de Pared",
  "Golpe de Xelor",
  "Esfera de Xelor",
  "Invocación de Dopeul Xelor",


  "Cara o Cruz",
  "Suerte de Zurcarák",
  "Salto del Felino",
  "Farol",
  "Percepción",
  "Contragolpe",
  "Trébol",
  "Todo o Nada",
  "Ruleta",
  "Topkaj",
  "Lengua Raspadora",
  "Rueda de la Fortuna",
  "Garra Invocadora",
  "Espíritu Felino",
  "Olfato",
  "Reflejos",
  "Garra Juguetona",
  "Garra de Ceangal",
  "Rekop",
  "Destino de Zurcarák",
  "Invocación de Dopeul Zurcarák",

  "Palabra Prohibida",
  "Palabra de Pavor",
  "Palabra Curativa",
  "Palabra Sanadora",
  "Palabra Hiriente",
  "Palabra Estimulante",
  "Palabra de Prevención",
  "Palabra Drenaje",
  "Palabra Revigorizante",
  "Regeneración",
  "Palabra de Espina",
  "Disipar",
  "Palabra Vampírica",
  "Palabra de Sacrificio",
  "Palabra de Amistad",
  "Palabra de Inmovilización",
  "Palabra de Vuelo",
  "Palabra de Silencio",
  "Palabra de Altruismo",
  "Palabra de Reconstitución",
  "Invocación de Dopeul Aniripsa",

  "Salto",
  "Intimidación",
  "Presión",
  "Compulsión",
  "Espada Divina",
  "Espada del Destino",
  "Guía de Valentía",
  "Amplificación",
  "Espada Destructora",
  "Corte",
  "Soplido",
  "Vitalidad",
  "Espada del Juicio",
  "Potencia",
  "Mutilación",
  "Tempestad de Potencia",
  "Espada Celeste",
  "Concentración",
  "Espada de Yopuka",
  "Ira de Yopuka",
  "Invocación de Dopeul Yopuka",


  "Flecha de Retroceso",
  "Flecha Envenenada",
  "Flecha Mágica",
  "Flecha Helada",
  "Flecha Flamígera",
  "Disparo Lejano",
  "Flecha de Expiación",
  "Ojo de Topo",
  "Disparo Crítico",
  "Flecha Inmovilizadora",
  "Flecha Castigadora",
  "Disparo Potente",
  "Flecha Acosadora",
  "Flecha Azotadora",
  "Flecha Perseguidora",
  "Flecha Destructora",
  "Flecha Absorbente",
  "Flecha Ralentizante",
  "Flecha Explosiva",
  "Dominio del Arco",
  "Invocación de Dopeul Ocra",


  "La Bloqueadora",
  "Zarza",
  "Veneno Paralizante",
  "Sacrificio Muñequero",
  "Lágrima",
  "La Loca",
  "Zarza Tranquilizadora",
  "Potencia Silvestre",
  "La Sacrificada",
  "Temblor",
  "Conocimiento de los Muñecos",
  "Zarzas Múltiples",
  "Árbol",
  "Viento Envenenado",
  "La Hinchable",
  "Zarzas Agresivas",
  "Hierba Loca",
  "Fuego Montés",
  "Zarza Insolente",
  "La Superpoderosa",
  "Invocación de Dopeul Sadida",

  "Castigo Forzado",
  "Pie del Sacrógrito",
  "Atracción",
  "Elusión",
  "Cambio",
  "Asalto",
  "Castigo Ágil",
  "Disolución",
  "Castigo Osado",
  "Castigo Espiritual",
  "Sacrificio",
  "Absorción",
  "Castigo Vitalesco",
  "Cooperación",
  "Transposición",
  "Castigo",
  "Furia",
  "Espada Voladora",
  "Transferencia de Vida",
  "Locura Sanguinaria",
  "Invocación de Dopeul Sacrógrito",

  "Tranka",
  "Resaca",
  "Puño Flamígero",
  "Terror",
  "Soplido Alcoholizado",
  "Vulnerabilidad Acuosa",
  "Vulnerabilidad Incandescente",
  "Karcham",
  "Vulnerabilidad Ventosa",
  "Estabilización",
  "Chamrak",
  "Vulnerabilidad Terrestre",
  "Deshonra",
  "Leche de Bambú",
  "Ola Marejadora",
  "Ira de Zatoishwan",
  "Frasco Explosivo",
  "Pandatak",
  "Pandenkulo",
  "Enlace Espirituoso",
  "Invocación de Dopeul Pandawa"



]