UPDATE spell SET is_global=0, is_team=0, is_self=0, is_ending_caster=0;
DROP TABLE IF EXISTS spell;

CREATE TABLE spell (
    id int(11) AUTO_INCREMENT PRIMARY KEY,
    id_class int(11) NOT NULL REFERENCES class(id),
    name varchar(255) NOT NULL,
    delay int(11) NOT NULL DEFAULT 1,
    is_global BOOLEAN NOT NULL DEFAULT FALSE,
    is_team BOOLEAN NOT NULL DEFAULT FALSE,
    is_self BOOLEAN NOT NULL DEFAULT FALSE,
    is_ending_caster BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);